### ISSUE TITLE
LilyGo LoRa32 V2.1 confusion

### ISSUE THREAD

**Issue by timmbogner** [radiolib-org/RadioBoards#3]
Hi Jan,
This is a great idea, thanks for putting it together. I have an ever-growing collection of LoRa modules that I use to test my Farm Data Relay System project, so I look forward to helping out here. I also hope to use this to simplify my own configuration system, of course!

I'm trying to figure out for sure which LilyGo board is which. The maintained board labeled "LilyGo TTGO LoRa32 v1/v2.1" looks like the configs for [this product](https://www.lilygo.cc/products/lora32-v1-0) or [this one](https://www.lilygo.cc/products/lora-v1-3), which I'll call the 1.0 and 1.3.

[This product](https://www.lilygo.cc/products/lora3), labeled on the Lilygo site as "v2.1", has pins that resemble what you have labeled as "TBeam". 

I guess this is all to point out that there's some discrepancy in what the 2.1 board refers to. I'm also curious which module is the "LilyGo TTGO LoRa32 v2" that you have the configs for. I actually have a brand new 2.1 if it helps, also a brand new 1.3, several old 1.0s, the T3S3s with each different Semtech chip, the new LoRa TWatch, and the radio modules for their TGrow soil sensors. I also just ordered an assortment of non-ESP Adafruit Feather Lora boards to test on my system. I'll contribute them all in time!

**Comment by timmbogner** [comment]
I have a confession: I only just noticed that in Arduino there is a sub-menu to select the board variant after you select "TTGO LoRa32 OLED".  In an indirect way, that's cleared up some of my confusion. I've also learned that what I was calling the "2.1" is probably more properly called the "1.6".

I've learned enough to see this is mostly my own confusion, so I'll close this for now.

**Comment by jgromes** [comment]
Sorry, I did not manage to react to this in time ... I admit it is possible there is some slight confusion regarding the different versions of LoRa32. To be honest I'm somewhat confused by it myself, so I can't rule out that there is some issue with the pin mapping.

Although, the LoRa32 pinmaps were taken from RadioLib LoRaWAN examples, which I think were tested - @StevenCellist please correct me if I'm wrong.

**Comment by StevenCellist** [comment]
The TTGO LoRa32 V2.1 aka V1.6.1 (yeah....) has been used extensively as a testing board during development, so as long as @jgromes did his homework right when copying it over to RadioBoards, yes, the V2.1==V1.6.1 should work all good.

@timmbogner am looking forward to your contributions!
